### PR TITLE
This is using Streams3

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by shinnn** [comment]
https://github.com/grncdr/merge-stream/pull/19 has been merged so *merge-stream* is now using Streams3.

**Comment by grncdr** [comment]
@shinnn

**Comment by stevemao** [comment]
still better to mention it in the readme

**Comment by shinnn** [comment]
@stevemao Could you update this PR?

**Comment by stevemao** [comment]
alright

**Comment by stevemao** [comment]
Done :)

**Comment by stevemao** [comment]
Done :)

**Comment by shinnn** [comment]
@stevemao Thanks!

**Pull request merged**
