### PR TITLE
Test on 'iojs' and '0.12'

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by shinnn** [comment]
+1

**Comment by stevemao** [comment]
The current one is wrong. `0.10` means your testing on `0.1`. You need to quote it to test on `'0.10'`.

**Comment by grncdr** [comment]
sorry I didn't see this one, can you please rebase?

**Comment by grncdr** [comment]
@shinnn feel free to merge this yourself as well :smile:

**Comment by stevemao** [comment]
rebased

**Comment by shinnn** [comment]
I prefer `node` rather than `0.12`.

http://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Choosing-Node-versions-to-test-against

> Specifying `node` or `stable` will run using the latest stable Node.js release

**Comment by stevemao** [comment]
better?

**Comment by shinnn** [comment]
Single quotes, please.

**Comment by stevemao** [comment]
done. i was trying to do minimum changes :)

**Comment by shinnn** [comment]
Ah, sorry I didn't check the existing style. Merging this anyway.

**Comment by shinnn** [comment]
@stevemao Thanks!

**Comment by stevemao** [comment]
Thanks. Can you make a release?

**Comment by shinnn** [comment]
I'm considering whether 0.2.0 or 1.0.0.

I'd like to hear your opinion, @grncdr.

**Comment by stevemao** [comment]
I think 1.0.0 should be fine :)

**Comment by grncdr** [comment]
If there's no API change, I'd say let's do `0.1.9` _and_ `1.0.0`. `0.1.9` so that users of semver ranges get it, and `1.0.0` because this module is actually pretty stable and in wide use.

**Comment by stevemao** [comment]
@grncdr because it switches from stream2 to 3 so you should at least do a minor release :)

**Comment by stevemao** [comment]
Also we added `isEmpty` (will probably be replaced #21) so there is an enhancement.

**Comment by grncdr** [comment]
> @grncdr because it switches from stream2 to 3 so you should at least do a minor release :)

I definitely don't see the point in doing a `0.2.0`. There's no need to bump minor for an enhancement pre `1.0.0`. If the switch to streams3 changes the behaviour in a way that can be observed by users then `1.0.0` makes the most sense to me.

**Pull request merged**
