### PR TITLE
Propagate source stream errors through output

### LINKED ISSUE #24: Errors are not propagated
Currently, errors that are created inside of the mergeStream are not propagated out of it.  As an example:

```js
// If an error occurs in streamOne or streamTwo, neither reject nor resolve is called. 
// The stream simply hangs.
mergeStream(streamOne, streamTwo)
  .on('error', reject)
  .on('finish', resolve);
```

This is unexpected behavior to me and I suspect all users, since they have no way to consume/handle errors. Because I am merging multiple streams into one, I would expect that merge stream to propagate all errors that occur in the streams that make it up. Otherwise they are lost with no way to handle them.

This was originally filed in issue #13, but I believe the OP was asking for a way to propagate errors down any chain of Node.js streams. So I'm reopening here with a more specific focus to merge-stream.

@grncdr wdyt? Is there any reason that this shouldn't be default behavior?

### PR DESCRIPTION
**Pull request by FredKSchott**
Fixes #24

### CODE REVIEW

**Comment by stevemao** [comment]
@shinnn @grncdr 

@FredKSchott presented a convincing argument. I think this behaviour is expected :)

**Comment by FredKSchott** [comment]
No problem, Thanks for the quick response! 

Test added

**Comment by stevemao** [comment]
ping @shinnn, could you merge this and make a new release :)
if you are too busy, can you add me to the npm package? Thanks.

**Comment by shinnn** [comment]
Strictly speaking, this change requires major version bump. But it can be also said that this PR is just a bug fix.

@stevemao @FredKSchott I'd like to hear your opinion.

**Comment by stevemao** [comment]
I think this is a bug fix.

**Comment by shinnn** [comment]
Published v1.0.1 to npm.

> can you add me to the npm package?

@stevemao ✨ 

```
$ npm owner add stevemao merge-stream
+ stevemao (merge-stream)

$ npm owner ls merge-stream
grncdr <glurgle@gmail.com>
shinnn <snnskwtnb@gmail.com>
stevemao <maochenyan@gmail.com>
```

**Comment by stevemao** [comment]
Cheers man ⭐️

**Comment by FredKSchott** [comment]
Thanks everyone! Looking forward to using this

**Pull request merged**
